create table if not exists public.typing_scores (
  id bigint generated by default as identity primary key,
  username text not null check (char_length(username) between 2 and 24),
  words integer not null check (words >= 0),
  accuracy integer not null check (accuracy between 0 and 100),
  created_at timestamptz not null default now()
);

create index if not exists typing_scores_rank_idx on public.typing_scores (words desc, accuracy desc, created_at asc);
alter table public.typing_scores enable row level security;
create policy "scores are publicly readable" on public.typing_scores for select using (true);
create policy "scores can be submitted" on public.typing_scores for insert with check (true);
